### ISSUE TITLE
Can't install, since the folder does not exist.

### ISSUE THREAD

**Issue by sebinsua** [notablemind/jupyter-nodejs#2]
This happens:

```shell
➜  package  node install.js                    
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/Users/sebinsua/.ipython/kernels/nodejs/kernel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1152:15)
    at Object.<anonymous> (/Users/sebinsua/package/install.js:15:4)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:124:18)
```

I will create the folder manually.

**Comment by stuaxo** [comment]
Just hit this, it needs to do whatever the equivilent of

```mkdir -p ~/.ipython/kernels``` 

before running that line

**Comment by mayankasthana** [comment]
I am having the same problem. 
It did get solved by `mkdir -p ~/.ipython/kernels` but it would be great if this could be handled automatically
