### ISSUE TITLE
Error: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by csells** [notablemind/jupyter-nodejs#23]
~/Downloads/package$ node install
module.js:339
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/csells/Downloads/package/install.js:4:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
~/Downloads/package$

**Comment by csells** [comment]
and just realized my own error.
