### ISSUE TITLE
Can't boot kernel

### ISSUE THREAD

**Issue by ryan-williams** [notablemind/jupyter-nodejs#30]
After following the installation instructions:

```
$ ipython console --kernel nodejs
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
/Users/ryan/c/jupyter-nodejs/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: dlopen(/Users/ryan/c/jupyter-nodejs/node_modules/zmq/build/Release/zmq.node, 1): Library not loaded: libzmq.3.dylib
  Referenced from: /Users/ryan/c/jupyter-nodejs/node_modules/zmq/build/Release/zmq.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (/Users/ryan/c/jupyter-nodejs/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/ryan/c/jupyter-nodejs/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
Jupyter Console 4.1.1


ERROR: Kernel did not respond

Shutting down kernel
```

After `Jupyter Console 4.1.1` it hangs for a while and takes a few minutes before exiting. Any idea what's going wrong? I have `brew install`ed `zmq` and `czmq` and tried the `wget`/`mv` workarounds listed [here](https://github.com/IRkernel/IRkernel/issues/50) to no avail.

**Comment by jaredly** [comment]
this is a result of the `zmq` module not installing correctly. if that happens, try deleting `jupyter-nodejs/node_modules` and re-running `npm install`
