### ISSUE TITLE
Cannot find module 'babel-runtime/helpers/class-call-check'

### ISSUE THREAD

**Issue by kxxoling** [notablemind/jupyter-nodejs#32]
Error appears when run:

``` js
%%babel
class Awesome {
  constructor() {
    console.log('yeah!')
  }
}
```

in notebook after `%load_ext babel`.

```
Error: Cannot find module 'babel-runtime/helpers/class-call-check'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/windrunner/jupyter-nodejs/build/context.js:73:16
    at require (/home/windrunner/jupyter-nodejs/build/context.js:53:27)
    at Object.Contextify.sandbox.run (/home/windrunner/jupyter-nodejs/node_modules/contextify/lib/contextify.js:12:24)
    at Context.rawRun (/home/windrunner/jupyter-nodejs/build/context.js:168:23)
    at Domain.<anonymous> (/home/windrunner/jupyter-nodejs/build/context.js:188:27)
    at Domain.run (domain.js:228:14)
```

My node and npm version:

```
$ node -v
v5.11.1
$ npm -v
3.8.6
```

**Comment by jaredly** [comment]
just added the missing babel-runtime package. lmk if you run into any more issues!
