### ISSUE TITLE
Tab completion unresponsive, raising Exception in thread Thread-4 after four times pressing tab.

### ISSUE THREAD

**Issue by fluteguitar** [notablemind/jupyter-nodejs#47]
Below are are the error message of testing auto-completion featur. ```Date.``` does not pop up suggestion expected.
```In [2]: Date.Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/interface.py", line 860, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/lib/python3.5/dist-packages/jupyter_console/ptshell.py", line 110, in get_completions
    cursor_pos=document.cursor_position
  File "/usr/local/lib/python3.5/dist-packages/jupyter_console/completer.py", line 39, in complete_request
    msg = self.client.shell_channel.get_msg(timeout=self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty```

**Comment by uscmule** [comment]
Similar issue here

$ python3 --version
Python 3.5.2

$ npm -v
5.5.1

$ node -v
v8.9.0

$ uname -a
Linux ubuntu 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ git log
commit 1388e1957792ef167ccfc7a9cf6c64c3950ded76

$ jupyter console --kernel nodejs
Jupyter console 5.2.0

NodeJS For your Jupyter experience!


In [1]: Date.Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/lib/python3.5/dist-packages/jupyter_console/ptshell.py", line 111, in get_completions
    cursor_pos=document.cursor_position
  File "/usr/local/lib/python3.5/dist-packages/jupyter_console/completer.py", line 39, in complete_request
    msg = self.client.shell_channel.get_msg(timeout=self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

**Comment by leonprou** [comment]
Yes I have the same error on Mac OS. But autocompletion for some words is working, like for `Number` and `console`.
