### ISSUE TITLE
Cannot do `%history`

### ISSUE THREAD

**Issue by sindhus** [notablemind/jupyter-nodejs#8]
hi!

Thanks for writing this. Am new to javascript. I used to do `history` in ipython python kernel and get all recent commands I executed. When I try this out in your kernel:

```
In [20]: %history
> %history
series 1
Error: Unknown line magic: history
    at Context.lineMagic (/Users/sindhus/Downloads/package/build/context.js:96:21)
    at /Users/sindhus/Downloads/package/build/context.js:328:25
    at /Users/sindhus/Downloads/package/node_modules/async/lib/async.js:607:21
    at /Users/sindhus/Downloads/package/node_modules/async/lib/async.js:246:17
    at iterate (/Users/sindhus/Downloads/package/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/Users/sindhus/Downloads/package/node_modules/async/lib/async.js:162:9)
    at _asyncMap (/Users/sindhus/Downloads/package/node_modules/async/lib/async.js:245:13)
    at Object.mapSeries (/Users/sindhus/Downloads/package/node_modules/async/lib/async.js:228:23)
    at Object.async.series (/Users/sindhus/Downloads/package/node_modules/async/lib/async.js:605:19)
    at Context.execute (/Users/sindhus/Downloads/package/build/context.js:333:26)
```

Can you please fix this? Thank you.

**Comment by sindhus** [comment]
I also can't seem to do `%lsmagic` to see all available magic functions.

**Comment by jaredly** [comment]
Oh yeah, I haven't implemented those. I'll go ahead and do that

**Comment by crutchcorn** [comment]
It would also be nice to have `%paste`, which is what I wanted to use this project for
